import libs = libminifb%lib{minifb}

exe{noise}:            {c}{noise}              $libs
exe{input_events}:     {c}{input_events}       $libs
# exe{input_events_cpp}: {cxx}{input_events_cpp} $libs
exe{multiple_windows}: {c}{multiple_windows}   $libs libm%lib{m}
exe{hidpi}:            {c}{hidpi}              $libs
exe{fullscreen}:       {c}{fullscreen}         $libs

./: exe{noise} \
    exe{input_events} \
    exe{multiple_windows} \
    exe{hidpi} \
    exe{fullscreen} \
    # exe{input_events_cpp}
