import libs = libminifb%lib{minifb}

exe{noise}:            {c}{noise}              $libs
exe{input_events}:     {c}{input_events}       $libs
exe{input_events_cpp}: {cxx}{input_events_cpp} $libs
exe{multiple_windows}: {c}{multiple_windows}   $libs libm%lib{m}
exe{hidpi}:            {c}{hidpi}              $libs
exe{fullscreen}:       {c}{fullscreen}         $libs

# Disable all tests. There is no auto-checks in the original repo.
# Technically, we could use testscripts and parse logs, but it makes
# no sense in this (third party) package.
exe{noise}:            test = false 
exe{input_events}:     test = false 
exe{input_events_cpp}: test = false 
exe{multiple_windows}: test = false 
exe{hidpi}:            test = false 
exe{fullscreen}:       test = false 

./: exe{noise} \
    exe{input_events} \
    exe{multiple_windows} \
    exe{hidpi} \
    exe{fullscreen} \
    exe{input_events_cpp}
